name: Update Members Data

# Trigger the action only when a pull_request is made to the main branch
# when changes are commited to the members files
on:
  pull_request:
    branches: [ main ]
    paths:
    - 'src/_data/members/members.json'
    - 'src/_data/members/core.json'
    - 'src/_data/members/teams.json'

  # Also run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-member-data:
    runs-on: ubuntu-latest

    steps:
      # Checkout the merged source code from PR
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Setup node v 14.x with npm and yarn
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      
      # Cache yarn node_modules (save 40 seconds)
      # as seen in https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - run: echo "::set-output name=dir::$(yarn cache dir)"
        id: yarn-cache-dir-path

      - name: Use yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      
      # Yarn install but prioritize the cache with --prefer-offline
      - name: Install packages
        run: yarn install --prefer-offline

      - name: Update members data
        run: yarn update-member-data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push changes in members data
        env:
          PR_ID:  {{github.event.pull_request.title}} #{{github.event.pull_request.number}}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add src/_data/members/memberData.json
          git commit -m "chore: update membersData.json after merging $PR_ID"
          git push origin main
